### ISSUE TITLE
Can't sign 0285FB6900D102030550F20A34908FFBC0BFAC35 locally

### ISSUE THREAD

**Issue by renyuneyun** [archlinuxcn/archlinuxcn-keyring#14] opened 2018-02-22 13:30 UTC
When installing `archlinuxn-keyring` today, I notice a complaint stating that:
```
  -> 正在本地签名密匙 0285FB6900D102030550F20A34908FFBC0BFAC35...
==> 错误： 0285FB6900D102030550F20A34908FFBC0BFAC35无法在本地签署。
```
All other keys are (l)signed successfully.

Is this key expired? How can I inspect it to sigure out what went wrong?

(I'm using English because fcitx is not configured yet...)

**Comment by farseerfc** [comment] 2018-02-22 14:12
Does reinstalling `archlinuxcn-keyring 20180221-2` reproduce the same error?

As you may notice, installing archlinuxcn-keyring will trigger "Updating trust database" TWICE, once by calling `pacman-key --populate`, and again by calling `gpg --check-trustdb --batch --yes`, for the reason here https://github.com/archlinuxcn/repo/issues/300#issuecomment-261963789 . The second time applying `--yes` to `--batch` will force an update even it is considered not being needed. Apparently this force update is able to fix some issue when gpg considered it being not neccessory. 

I am now considering to do the same thing for `--lsign-key --batch`  in `pacman-key` ...

**Comment by renyuneyun** [comment] 2018-02-22 14:24
Yes, reinstalling `archlinuxcn-keyring 20180221-2` produce the same error.

How to list the keys in `/usr/share/pacman/keyrings/archlinuxcn*`?
I tried `gpg --keyring /usr/share/pacman/keyrings/archlinuxcn.gpg --list-keys` but gpg says `gpg: [don't know]: invalid packet (ctb=2d)`; `pacman-key` seems not offering this function.

**Comment by renyuneyun** [comment] 2018-02-22 14:25
Sidenote: I'm on a fresh Arch system.

**Comment by farseerfc** [comment] 2019-07-26 06:53
Closing this for now as long time has passed

**Closed by farseerfc** 2019-07-26 06:53 UTC
